import{getMeta}from'./db.js';import{pair}from'./auth.js';import{syncNow,syncStatus,startAutoSync}from'./sync.js';import*as views from'./views.js';
const app=document.querySelector('#app'),setup=document.querySelector('#setup'),view=document.querySelector('#view'),title=document.querySelector('#page-title'),syncButton=document.querySelector('#sync-button');const titles={home:'Dashboard',activity:'Activity',add:'Add Entry',accounts:'Accounts',more:'More'};let route='home';
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)}
async function updateStatus(){const s=await syncStatus();syncButton.textContent=s.conflicts?'Conflict':s.pending?`${s.pending} pending`:s.status==='syncing'?'Syncing…':navigator.onLine?'Synced':'Offline'}
async function navigate(next){route=next in views?next:'home';title.textContent=titles[route];view.innerHTML=await views[route]();await views.bind(route,navigate,toast);view.focus();document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.route===route?'page':'false'));updateStatus()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.route));syncButton.onclick=async()=>{try{const r=await syncNow();toast(`${r.uploaded} uploaded, ${r.downloaded} downloaded`);navigate(route)}catch(e){toast(e.message)}};addEventListener('household-sync',updateStatus);
document.querySelector('#pair-form').onsubmit=async e=>{e.preventDefault();const error=document.querySelector('#pair-error');error.textContent='';try{await pair(document.querySelector('#device-name').value,document.querySelector('#pairing-code').value);setup.classList.add('hidden');app.classList.remove('hidden');await navigate('home');startAutoSync()}catch(ex){error.textContent=ex.code==='INVALID_PAIRING_CODE'?'That pairing code is invalid, expired, or already used.':ex.message}};
async function init(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');if(await getMeta('device_token')){app.classList.remove('hidden');await navigate('home');startAutoSync();syncNow().then(()=>navigate(route)).catch(()=>updateStatus())}else setup.classList.remove('hidden')}
init();
