import{post,ApiError}from'./api.js';import{all,get,getMeta,setMeta,transaction}from'./db.js';import{config}from'./auth.js';
const STORE={member:'members',account:'accounts',category:'categories',financial_entry:'financial_entries'};const ORDER={member:0,account:1,category:2,financial_entry:3};const LIMIT=10;let running=null;
export async function localMutation(entityType,operation,data){const entityId=data.id||crypto.randomUUID(),changeId=crypto.randomUUID(),store=STORE[entityType],now=new Date().toISOString();const existing=await get(store,entityId);const entity={...(existing||{}),...data,id:entityId,updated_at:now};if(!entity.created_at)entity.created_at=now;if(['archive','delete'].includes(operation))entity.deleted_at=now;if(operation==='restore')entity.deleted_at=null;const change={changeId,entityType,entityId,operation,baseServerRevision:Number(existing?.server_revision||0),data:syncPayload(entity),createdAt:now,attemptCount:0,lastError:null};await transaction([store,'outbox'],'readwrite',tx=>{tx.objectStore(store).put(entity);tx.objectStore('outbox').put(change)});dispatchEvent(new CustomEvent('household-local-change'));return entity}
function syncPayload(row){const data={...row};delete data.server_revision;for(const [key,value]of Object.entries(data))if(value===undefined)delete data[key];if(data.amount!==undefined)data.amount=Number(data.amount).toFixed(2);return data}
async function buildRequest(){const cfg=await config();if(!cfg.deviceToken)throw new ApiError('Pair this device to synchronize.','INVALID_DEVICE');const changes=(await all('outbox')).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(0,LIMIT).map(c=>({...c,attemptCount:undefined,lastError:undefined,createdAt:undefined}));return{cfg,changes,lastRevision:Number(await getMeta('last_server_revision',0))}}
export async function syncNow(){if(running)return running;running=run().finally(()=>{running=null});return running}
async function run(){await setMeta('sync_status','syncing');dispatchEvent(new CustomEvent('household-sync'));try{let uploaded=0,downloaded=0,conflictCount=0,currentRevision=Number(await getMeta('last_server_revision',0));while(true){const{cfg,changes,lastRevision}=await buildRequest();const result=await post({action:'sync',deviceId:cfg.deviceId,deviceToken:cfg.deviceToken,lastServerRevision:lastRevision,changes});if(result.householdId&&cfg.householdId&&result.householdId!==cfg.householdId)throw new ApiError('This device is linked to a different household. Sync stopped.','HOUSEHOLD_MISMATCH');await applyResponse(result,changes);uploaded+=result.acknowledgments?.length||0;downloaded+=result.changes?.length||0;conflictCount+=result.conflicts?.length||0;currentRevision=result.currentRevision;if(conflictCount||(await all('outbox')).length===0)break}await setMeta('sync_status',conflictCount?'conflict':'synced');return{uploaded,downloaded,conflicts:conflictCount,revision:currentRevision}}catch(error){await setMeta('last_sync_error',error.message);await setMeta('sync_status',error.code==='INVALID_DEVICE'?'authorization_required':navigator.onLine?'error':'offline');throw error}finally{dispatchEvent(new CustomEvent('household-sync'))}}
async function applyResponse(result,sent){const stores=['metadata','outbox','conflicts',...Object.values(STORE)];await transaction(stores,'readwrite',tx=>{const sentMap=new Map(sent.map(c=>[c.changeId,c]));for(const conflict of result.conflicts||[]){const local=sentMap.get(conflict.changeId);tx.objectStore('conflicts').put({id:crypto.randomUUID(),changeId:conflict.changeId,entityType:conflict.entityType||local?.entityType,entityId:conflict.entityId||local?.entityId,localData:local?.data||conflict.localData,cloudData:conflict.serverData||conflict.cloudData,cloudRevision:Number(conflict.serverRevision||0),detectedAt:new Date().toISOString(),resolvedAt:null});tx.objectStore('outbox').delete(conflict.changeId)}for(const change of [...(result.changes||[])].sort((a,b)=>(ORDER[a.entityType]-ORDER[b.entityType])||(a.revision-b.revision))){const store=STORE[change.entityType];if(!store)continue;tx.objectStore(store).put({...change.data,id:change.entityId,server_revision:change.revision})}for(const ack of result.acknowledgments||[]){const local=sentMap.get(ack.changeId);if(!local)continue;tx.objectStore('outbox').delete(ack.changeId);const store=tx.objectStore(STORE[local.entityType]);const req=store.get(local.entityId);req.onsuccess=()=>{if(req.result)store.put({...req.result,server_revision:ack.serverRevision})}}const meta=tx.objectStore('metadata');meta.put({key:'last_server_revision',value:result.currentRevision});meta.put({key:'last_sync_at',value:new Date().toISOString()});meta.put({key:'last_sync_error',value:null})})}
export async function syncStatus(){return{status:await getMeta('sync_status','idle'),lastSyncAt:await getMeta('last_sync_at'),lastError:await getMeta('last_sync_error'),pending:(await all('outbox')).length,conflicts:(await all('conflicts')).filter(c=>!c.resolvedAt).length,revision:Number(await getMeta('last_server_revision',0))}}
export async function conflicts(){return(await all('conflicts')).filter(c=>!c.resolvedAt)}
export async function resolveConflict(id,resolution){const conflict=await get('conflicts',id);if(!conflict||conflict.resolvedAt)return;if(resolution==='cloud'){await transaction([STORE[conflict.entityType],'conflicts'],'readwrite',tx=>{tx.objectStore(STORE[conflict.entityType]).put({...conflict.cloudData,id:conflict.entityId,server_revision:conflict.cloudRevision});tx.objectStore('conflicts').put({...conflict,resolution:'cloud',resolvedAt:new Date().toISOString()})})}else{const now=new Date().toISOString(),change={changeId:crypto.randomUUID(),entityType:conflict.entityType,entityId:conflict.entityId,operation:'update',baseServerRevision:conflict.cloudRevision,data:syncPayload(conflict.localData),createdAt:now,attemptCount:0,lastError:null};await transaction(['outbox','conflicts'],'readwrite',tx=>{tx.objectStore('outbox').put(change);tx.objectStore('conflicts').put({...conflict,resolution:'local',resolvedAt:now})})}dispatchEvent(new CustomEvent('household-local-change'))}
export function startAutoSync(){addEventListener('online',()=>syncNow().catch(()=>{}));addEventListener('household-local-change',()=>syncNow().catch(()=>{}));setInterval(()=>{if(navigator.onLine)syncNow().catch(()=>{})},120000)}
